import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

import JssStyleRegistry from '@/lib/registry';

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <JssStyleRegistry>{children}</JssStyleRegistry>
            </body>
        </html>
    );
}
